VisionSystemsInc/vsi_common

linux/docker_entrypoint.bsh
quick fix for the "link_destination [$y]: unbound variable" error. as elements are removed from this array they leave holes which must be skipped over on the next pass. not sure how we've never seen this before.
=> jump over holes in the array

linux/docker_functions.bsh
on Windows, docker-compose tries to expand this to .\\docker-compose.yml which errors out with "No Such File or Directory"
=> windows shell expansion

linux/just_functions.bsh, tests/test-just_functions.bsh
@scott-vsi Please check this and make sure I didn't break anything or miss any corner cases in the unit test. It's a core piece of `just`, and any 🐛 would be 😠 
---
Say `target1` takes multiple or all extra args, the separator can break this and continue to the next target
```
just target1 arg1 arg2 -- target2 arg3 arg4
```
This used to call `caseify target1 arg1 arg2 -- target2 arg3 arg4`, in which case, `target1` would use up all the args. 
But now its more `caseifty target1 arg1 arg2; caseify target2 arg3 arg4`. Making it equivalent to `justify target1 arg1 arg2; justify target2 arg3 arg4`
Addition test examples welcome
**NOTE:** Nothing to do with `get_args`
=> Break justify chains with separator

linux/new_just
The new pipenv pattern has a few rough edges
1. Running in the `dep_pipenv` stage didn't have `/venv` populated, so if this was done before the volume was created, it was created with nothing, creating awful synchronization issues.
1. The `dep_pipenv` stage was root. So running anything in there created Root files that had to be patched. This kept growing to the point where it made more sense just to use the vsi just entrypoint instead and run as user.
So now the stage is moved after the `pipenv sync` command, and add the vsi entrypoint, solving both of these problems. It is done afterwards to save on docker build cache time when vsi common changes.
=> Now the pipenv run stage runs as not root

linux/just_entrypoint.sh
While `docker_setup_user` in `just_entrypoint_function` provides a default value for `DOCKER_USERNAME` if not specified (`docker_setup_user` is called through line 87 in the quoted code), that default value is not available when attempting to rerun the entrypoint.  Provide a default value for `DOCKER_USERNAME` if left unspecified.
https://github.com/VisionSystemsInc/vsi_common/blob/1d3de09b2b7286aef9b6fb9871641b095a6a3d43/linux/just_entrypoint.sh#L76-L99
=> default DOCKER_USERNAME in just_entrypoint

docker/tests/bash_test.Dockerfile, docker/vsi_common/bashcov.Dockerfile, docker/vsi_common/sphinx.Dockerfile, linux/dir_tools.bsh, linux/docker_functions.bsh, linux/just_docker_functions.bsh, linux/just_entrypoint.sh, linux/just_entrypoint_functions, linux/just_singularity_functions.bsh, linux/new_just, linux/singularity_functions.bsh, tests/test-docker_functions.bsh, tests/test-just_singularity_functions.bsh, tests/test-singularity_functions.bsh
- Added `docker-compose-list-internal-volumes`, which will list all declared internal volumes in the entire docker-compose file, not for any specific service, and lists them even if no service references it
- Added `docker-compose clean --all` target now, which will clean all the internal volumes in the entire docker-compose.yml file.
- Added `/usr/local/share/just/root_run_patch/` and `/usr/local/share/just/user_run_patch/` to the just entrypoint, overrideable with `JUST_ROOT_PATCH_DIR` and `JUST_USER_PATCH_DIR`
=> Debug support

linux/just_git_functions.bsh
Git 2.11 was not happy with the `--`, we'll try using this without the `--` for now, and see how it works. 
This entire function needs a rewrite due to #186 anyways
=> Support git 2.11

linux/just_common.bsh, linux/just_singularity_functions.bsh, tests/test-just_singularity_functions.bsh
- Add /tmp first in singular run, so subsequent. Closes #208
- Add full path of `Justfile` in `JUST_HELP_FILES` so that just works
in other directories
- Fix singular import always writes to base directory, instead of
correct subdirectory
=> A few singularity fixes

.circleci/config.yml, .gitattributes, docs/conf.py, python/vsi/iglob.py, python/vsi/tools/dir_util.py, python/vsi/tools/file_util.py, python/vsi/tools/iter.py, python/vsi/tools/mpl_zoom.py, python/vsi/tools/natural_sort.py, python/vsi/tools/python.py, python/vsi/tools/redirect.py, python/vsi/tools/stdout_profile.py, python/vsi/tools/vdb.py, python/vsi/tools/vdb_ipdb.py, python/vsi/vxl/generate_scene_xml.py, python/vsi/windows/find_process.py, python/vsi/windows/named_pipes.py, vsi_common.env
Add intersphinx_mapping to sphinx docs conf.py, allowing documentation to appropriately cross-reference against other documentation. Note this drastically reduces the necessary nitpick_ignore list and should make future documentation have fewer errors.
Add --keep-going to circleci compile_docs to make visible all sphinx errors (not just the first one).
For windows compatibility, add `*.env eof=lf` to `.gitattributes` and `JUST_PATH_ESC` to `vsi_common.env`
=> sphinx cross-reference

linux/file_tools.bsh, linux/just_docker_functions.bsh
avoid 'Error: No such volume' message when trying to inspect a volume that isn't found (it may have already been deleted)
=> avoid 'Error: No such volume'

linux/just_docker_functions.bsh
The `docker stop` command also induces a `rm` on containers marked with the --rm flag. Therefore we have to wait until the container no longer exists to continue.
=> wait until the container no longer exists before continuing

linux/just_git_functions.bsh
GIT is left unquoted to support limited dry-run capability
=> GIT should not be quoted in this very unusual case

linux/just
Adds the ability to ignore certain exit codes and not print stack traces, for user friendliness
=> Added JUST_IGNORE_EXIT_CODES

docker/vsi_common/bashcov.Justfile, linux/just, linux/new_just, tests/quiz-testlib.bsh, tests/run_tests, tests/test-docker_compose_override.bsh, tests/test-docker_functions.bsh, tests/test-elements.bsh, tests/test-just_functions.bsh, tests/test-just_wrap.bsh, tests/test-new_just.bsh, tests/test-python_tools.bsh, tests/test-testlib.bsh, tests/testlib.bsh
Required failure and expected failure tests can only fail in designated fail zones now.
=> Restruct possible fails testlib

docker/vsi_common/sphinx.Justfile, docs/conf.py, linux/just_files/just_sphinx_functions.bsh
New `intersphinx` convenience functions for `just_sphinx_functions`, letting users display contents of intersphinx mapping files.  This is helpful when searching for the root cause of a broken intersphinx link in a documentation project.  
Additionally update intersphinx mapping for numpy.
=> Intersphinx

linux/just_files/just_ci_functions.bsh, linux/just_files/just_docker_functions.bsh
While `ci_load.py` handles multi-stage services very well, it does not handle multi-stage **recipes** such as `recipe_gdal`.  The final `ONBUILD` stage of a recipe is successfully loaded, but preceding recipe stages are not loaded.
Rather than update `ci_load.py` to also handle multi-stage recipes, we can instead combine `ci_load.py` with the recipe cache now on dockerhub @ [vsiri/ci_cache_recipes](https://hub.docker.com/repository/docker/vsiri/ci_cache_recipes) to introduce a new ci_load pattern inspired by `build_recipes-auto`.
We separate recipe (`ci_load_recipes-auto`) and service (`ci_load_services`) load to ensure all recipe & service multi-stage docker caches are correctly cached.  Projects may add the following to their just file to include ci_load capabilities:
```
ci_load) …
```
=> ci_load for multi-stage recipes

linux/ci_load.py, linux/just_files/just_ci_functions.bsh
Allow ci_load versioning - this is useful to "clear" the cache (set a new version that is not in the dockerhub cache) without actually removing any images from dockerhub. 
Add new `JUST_CI_*` variables to control version & docherhub repo for both the recipe and service cache.
=> ci_load version

linux/requirements.bsh, tests/test-requirements.bsh
`meet_requirements` add `==*` option for improved compatibility with pip-style requirements.  New unit tests for `==*`.
Remove `not` command from `meet_requirements` - in my understanding, `not` is only available in the testing library and not available at runtime.  Note any utility using the `not` command may succeed at test time but fail at runtime.
=> meet_requirements ==

.circleci/config.yml
Disable windows CircleCI build, as there is limited availability for open-source builds at this time.
=> disable circleci for windows

appveyor.yml
appveyor has not run `just test int git_mirror` as unzip was not installed.  After installing unzip, additional environment modifications are necessary to successfully run the test.
- remove extra git install (git & git-lfs already available)
- remove extra path modification (`MSYSTEM: MINGW64` already modifies path)
=> appveyor environment

appveyor.yml, linux/just_files/just_install_functions.bsh, tests/int/test-just_install_functions.bsh
New just targets for `just_install_functions` to create isolated sandbox installations of python (installed via conda), pipenv (installed via `30_get-pipenv` an isolated virtualenv), and cmake.  Intended use is to create isolated environments (primarily for windows) that do not conflict with system-level programs.
=> just_install_functions

.travis.yml, linux/just_files/just_install_functions.bsh, tests/int/test-just_install_functions.bsh
Minor updates to `just_install_functions`
- `conda-python-install` optional input for additional packages
- `pipenv-install` optional input for python activation script
- Activate travis test for mac
- update test for travis & new build pattern
=> just_install_functions update

linux/compat.bsh, linux/just_files/just_makeself_functions.bsh, tests/int/test-compat.bsh, tests/int/test-git_mirror.bsh, tests/int/test-just_git_airgap_repo.bsh, tests/int/test-new_just.bsh, tests/test-compat.bsh
`sed_flag_i` wasn't working on macOS. We had to change it to an array. It is now called `sed_flags_i` to highlight that it must be used as an array
=> Fix `sed_flag_i`

linux/compat.bsh, linux/git_mirror, tests/int/test-git_mirror.bsh, tests/int/test-just_git_airgap_repo.bsh, tests/test-compat.bsh
The incremental archive was way too big; it was including all of git's object files. These were being included because a local `git clone` uses hardlinks (by default) which affect the ctime of the files. That causes tar to treat them as changed and include them in the incremental archive.
=> Create smaller incremental archives

tests/quiz-testlib_setup.bsh, tests/test-testlib.bsh, tests/testlib.bsh
Now `setup` and `teardown` only run if at least one test is run
=> Testlib improvements

.circleci/config.yml, linux/just_files/just_install_functions.bsh, tests/int/test-just_install_functions.bsh
Update windows workflow for `just_install_functions::conda-install-python` to eliminate unwanted registry changes and shortcuts.  
- Include '/AddToPath=0 /RegisterPython=0` during temporary miniconda install
- Cleanup shortcuts via `"${CONDA}" remove -y -p "${conda_dir}" console_shortcut powershell_shortcut`
- Add test to ensure initial & final state of some windows registry keys are unchanged.
=> windows registry & shortcuts in conda-install-python

linux/just_files/just_install_functions.bsh
Add virtualenv options to `just_install_functions::pipenv-install`, including the optional virtualenv version (currently pinned to 20.0.33) and a previously downloaded virtualenv zipapp.
Update docker_recipes.
=> just_install_functions::pipenv-install virtualenv version

python/vsi/utils/mesh_utils.py
meshio doesn't like ply files with no "face" element in the header, even if there are 0.
=> add face element to ply header

linux/just_files/docker_compose_override
`generate_docker_compose_override` ensure bind-mount directories defined by `DOCKER_VOLUME_SOURCES` are created via `docker_premkdir`
=> docker_compose_override premkdir for bind-mount directories

.appveyor.yml, docs/linux/index.rst, linux/aliases.bsh, linux/common_source.sh, linux/compat.bsh, linux/compat_singularity.bsh, linux/cuda_info.bsh, linux/git_mirror, linux/just_files/docker_compose_override, linux/just_files/docker_functions.bsh, linux/just_files/just_env, linux/just_files/just_git_functions.bsh, linux/just_files/singularity_functions.bsh, linux/just_git_airgap_repo.bsh, linux/linux_accounts.bsh, linux/pipenv_functions.bsh, linux/requirements.bsh, linux/time_tools.bsh, tests/int/test-compat.bsh, tests/int/test-docker_compose_override.bsh, tests/int/test-docker_functions.bsh, tests/int/test-git_mirror.bsh, tests/int/test-just_git_airgap_repo.bsh, tests/int/test-just_git_functions.bsh, tests/int/test-new_just.bsh, tests/test-cuda_info.bsh, tests/test-docker_functions.bsh, tests/test-linux_accounts.bsh, tests/test-singularity_functions.bsh, tests/testlib.bsh
- Un-hardcode non-core external command
- Consistently add quotes around these aliases.
- The old rejected argument to leave the quotes off was to:
- Support corner cases like `FOO='echo foo'`
- At the sacrifice of supporting spaces, like `/foo/b a  r/stuff`
- However this is just adding unexpected behavior
- This can be also accomplished via `foo2(){ echo foo "${@}"); export -f foo2; export FOO=foo2`
- This will work unless bash calls python which calls bash
- Then you'll have to use an external file like `/tmp/foo2`
- The takeaway is there are more normal workarounds to cover this corner case, so the missing quotes are purge
- `DRYRUN` is a different entity, and not the same as an "alias"
=> Andy 20201105

linux/load_nvidia_uvm.py
Prevent accidentally loading a non-`.so` file (like a man page), and keep searching until either a success or no common dirs left to search
=> Improve load uvm script

linux/just_files/just_singularity_functions.bsh, pyproject.toml, python/vsi/test/test_python.py, python/vsi/tools/dir_util.py, python/vsi/tools/python.py, python/vsi/vendored/filelock.py
- Added a vendored version of `filelock`, so that we can add patches to it,
- Change the default ignore codes for singularity, so that failed start and stop instances don't spam a just stack.
- Fix (known) bug in `nested_update`, that errors on type changes, now replaces old types
- Added `is_dir_empty`
=> Andy 20210225

docker/vsi_common/sphinx.Justfile
update intersphinx capability to allow non-default `objects.inv` specification.  For example, django stores its object file at
https://docs.djangoproject.com/en/3.1/_objects
See first example here
https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping
=> intersphinx non-default objects.inv

.appveyor.yml
Recent appveyor error:
> C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S unzip"
warning: database file for 'ucrt64' does not exist (use '-Sy' to download)
error: failed to prepare transaction (could not find database)
Fix by refreshing package database for ucrt64 repository after system upgrade.
=> appveyor ucrt64 

linux/just_files/new_just, linux/uwecho.bsh, tests/int/test-new_just.bsh, tests/test-new_just.bsh
- The `.gitignore` writer was smart enough to work if a `.gitignore` file already exists. Extended the same logic to the `.dockerignore` and `.gitattributes` writers
- Make sure that these files end in newlines before appending lines
- "Tutorial comments" are in `##`, so a new user is more aware what they can delete
- Updated GDAL example to use new recipe
- Example app no longer starts a shell. It's an example of an app, not a shell. There will never be a shell target like this EVER again...
- NEW Shell target, starts a shell!!!
- Fixed issue in `new_just` when source, it was deleting the "curl compatibility temp file" too soon. Now it wait
- Further documented and added a warning how `uwecho` is not happy in an interactive terminal.
=> New just improvements

README.md, linux/compat.bsh, linux/just_files/new_just, linux/signal_tools.bsh, tests/testlib.bsh
There was a bug in bash 3.2 that wasn't running all of the traps in test that had more than one exit trap, and failed tests weren't being detected
=> Fix failed test not being caught

linux/just_files/just_install_functions.bsh, tests/int/test-just_install_functions.bsh
- update docker_recipes, now favoring `RECIPE_*` style environment variables in `30_get-pipenv`
- mimic  `RECIPE_*` style environment variables in `just_install_functions::pipenv-install`
- update default versions in `pipenv-install` (20.4.5 for virtualenv, 2020.11.15 for pipenv)
=> pipenv environment variables

linux/just_files/docker_functions.bsh, linux/python_tools.bsh, tests/test-python_tools.bsh
- Fix a minor variable leak in Just-docker-compose
- Added a literal version of converting a bash array to a string for `ast.literal_eval`, this will allow a user to make arrays of integers and floats, not just strings.
=> Python tools rewrite

.appveyor.yml, vsi_common.env
- update appveyor to use Visual Studio 2019 image, eliminating the need for several pacman workarounds
- stop testing centos6 as per https://github.com/VisionSystemsInc/vsi_common/pull/371#issuecomment-898593598
=> CI: ignore centos6, appveyor VS2019

linux/cuda_info.bsh, tests/test-versions.bsh
- Added Cuda 11.3.0 and Cuda 11.3.1
- It turns out Table 3 from the release notes is not what we want, it's really Table 2
- Completely regrouped all the Cuda 11.* sections to reflect this new understanding.
=> Updated cuda 11 info

linux/just_files/just_install_functions.bsh, tests/int/test-just_install_functions.bsh
New `just install conda` to install miniconda.  Includes new test.  Also update `just install conda-python` to make use of new conda installer function.
=> conda-install

Justfile, docker/tests/os.Dockerfile, linux/compat.bsh, linux/signal_tools.bsh, linux/versions.bsh, python/vsi/test/test_dir_util.py, python/vsi/test/test_vdb.py, python/vsi/tools/dir_util.py, tests/int/test-just_install_functions.bsh, tests/test-compat.bsh, tests/test-versions.bsh
- Fix bug causing every test to fail to even start properly on SLES 11.4  (in signal_tools)
- Fixes bug where failing tests on bash 3.2 didn't propagate the error code correctly (and added compat flag documenting this scenario)
- Fix could no longer build docker images on OSes pre-glibc 2.24
- Added `is_subdir` flag to skip dereferencing symlinks, so we can check is_subdir and ignore smylinks.
=> Other os fun

linux/just_files/just_singularity_functions.bsh
`just_singularity_functions` remove `-it` from docker call in `singularity_import`.  Interactive mode & tty do not appear necessary for this function.
=> remove '-it'

.github/workflows/macos.yml, linux/just_files/just_functions.bsh, linux/just_files/new_just
- After setting up a new project, I noticed a few issues/bugs
- `local.env` had no shebang
- `project.env` had no shebang
- There was no GDAL in the tutorial in Pipfile
- The libxml-devel was a bad example in the pipenv cache stage
- python3-dev is the right name on debian, and actually useful
- Added some steps in the comments no one reads on how to test that gdal
is properly working with numpy integration
=> Improve a few things in new_just

linux/just_files/new_just
Update new_just pattern. You can now skip pipenv sync on docker build.
This is sometimes important when you make a lot of changes, and the docker image no longer builds, and you need to relock on the new image, but can't build it to lock against. In this case you can now:
- `{PROJECT_PREFIX}_SKIP_PIPENV_SYNC=1 just build`
- `just pipenv lock`
- `just build` (optional, for due diligence)
=> Pipenv skip sync

linux/just_files/just_ci_functions.bsh
`just_ci_functions.bsh` - add `JUST_CI_CACHE_ARGS` and `JUST_CI_RECIPE_ARGS` to allow environment variable of ci_load arguments for services and recipes.
=> just_ci_functions arguments

linux/just_files/new_just
This is a common enough problem, and I don't see a significant side effect to not justify making this the default.
A few docker operations take an undefined amount of time while not communicating between the docker client (`docker-compose`) and docker daemon, e.g. during docker container creation, a large volume initialization can take longer than the default timeout of 30 seconds.
=> Add docker compose timeout by default

docs/conf.py
- update docker_recipes, including recipe_gdal update to manylinux2014
- bugfix: correct matplotlib intersphinx to https://matplotlib.org/stable
=> docker_recipes & docs

docker/vsi_common/docker-compose.yml, linux/ci_load.py
Fixes derived from terra_dsm circleci failures, which is using a more recent docker and docker-compose in the CircleCI cimg/python image.  Specific fixes:
- Add default source locations for sphinx bind-mounts
- ci_load optional compose_version
=> terra_dsm CI fixes

linux/just_files/docker_functions.bsh
The new docker-compose outputs `config` yaml differently than the old config. Instead of printing a multiline string in escaped form:
```yaml
redis-commander:
command: "sh -c '\n  echo -n '\"'\"'{\n    \"connections\":[\n      {\n      \
\  \"password\": \"'\"'\"' > /redis-commander/config/local-production.json\n\
\  cat \"/run/secrets/redis_password\" | sed '\"'\"'s|\\\\|\\\\\\\\|g;s|\"|\\\
\\\"|g'\"'\"' >> /redis-commander/config/local-production.json\n  echo -n '\"\
'\"'\",\n        \"host\": \"terra-redis\",\n        \"label\": \"terra\",\n\
\        \"dbIndex\": 0,\n        \"connectionName\": \"redis-commander\",\n\
\        \"port\": \"6379\"\n      }\n    ],\n    \"server\": {\n      \"address\"\
: \"0.0.0.0\",\n      \"port\": \"4567\",\n      \"httpAuth\": {\n        \"\ …
```
=> Fix incompatibility with docker-compose 2.x

linux/just_files/just_install_functions.bsh, tests/int/test-just_install_functions.bsh
Allow conda install using miniforge (rather than miniconda).  Update conda install tests to try both miniconda and miniforge.
=> miniforge conda install

linux/ci_load.py
ci_load allow pull to fail (typically occurs when images do not exist)
=> ci_load pull

linux/ci_load.py
control ci_load verbosity:
- `--quiet-pull` to eliminate progress bars during dockerhub image pull (progress bars can make CI output very hard to read)
- `--print-push-pull` to print push/pull configuration file (view services & cached images) 
- `--print-build` to print build configuration file (view services & cache_from values)
=> ci_load verbosity

linux/ci_load.py
`ci_load.py --other-repos <OTHER_REPO> ...` to optionally warm CI docker cache from more than one location.  This is useful if the cache is moved to a new dockerhub location, or for new "blueprint" docker patterns where default dockers stored in one dockerhub location are useful to warm a project-specific docker cache. 
Specific changes include:
- separate pull & push configurations, to allow pulling from multiple caches but push only to the main cache
- multiple cache locations - pull from multiple caches, `cache_from` with multiple caches
- add `--ignore-pull-failures` to pull, pulling what's available and ignoring what's not yet available 
- Note the push/pull yaml files are only briefly written to disk during push/pull operations; the class now stores push/pull dictionaries instead of …
=> ci_load --other-repos

.gitmodules, tests/int/test-just_git_airgap_repo.bsh
Add docker_blueprints as submodule.  Docker blueprints are similar to docker recipes, but blueprints are typically more complicated multi-stage builds, don't use ONBUILD, and may have inter-blueprint dependencies (e.g., PDAL blueprint needs GDAL blueprint).
Note this PR required minor updates to `tests/int/test-just_git_airgap_repo.bsh` to accommodate the new submodule.
=> docker_blueprints

linux/just_files/just_ci_functions.bsh
`just ci load-blueprint` to run `ci_load.py` for a single blueprint.  The result is saved to the project cache at `$JUST_CI_CACHE_REPO`, warmed from the blueprint cache at `$JUST_CI_BLUEPRINT_REPO`.
Additionally force `just ci load-recipes` to always include the `--no-push` flag, as `docker_recipes` is the only repo that should ever push to the recipe CI cache.
=> ci_load blueprint

linux/ci_load.py, linux/just_files/just_ci_functions.bsh
`ci_load.py` do not push by default
- mutually exclusive options for `--pull`/`--no-pull`, `--build`/`--no-build`, `--push`/`--no-push`
- do not push by default
- other defaults remain the same - pull & build by default
Additional update for `just ci load-recipes` as forced `--no-push` is no longer necessary
=> ci_load --push

linux/dir_tools.bsh, tests/test-dir_tools.bsh
Adds a way to reproduce `--strip-components` from `tar`, during `cp`
=> Strip copy

.circleci/config.yml, linux/cuda_info.bsh, linux/just_files/just_functions.bsh, tests/test-cuda_info.bsh, tests/test-test_utils.bsh, tests/test_utils.bsh
- Added up to CUDA 11.8
- Compatible and minimum drivers were mixed up for CUDA 11, they are now separated
- Refactored most of the cuda_info code to repeat the same information less, because CUDA is releasing new versions so frequently
- Added an assert_set and assert_unset to test_utils
=> Cuda update

linux/cuda_info.bsh, tests/test-cuda_info.bsh
CUDA card info (`CUDA_CARDS`, `CUDA_CARD_ARCHES`, & `CUDA_CARD_FAMILIES`) from `nvidia-smi` using the command
```
nvidia-smi --query-gpu=gpu_name,compute_cap --format=csv,noheader
```
CUDA card info (`CUDA_CARDS` only) from `wmic.exe` using the command
```
wmic.exe PATH win32_VideoController GET AdapterCompatibility,Name /format:csv
```
=> cuda query

linux/just_files/docker_compose_override, linux/nvidia_tools.bsh, tests/test-docker_compose_override.bsh
Add the `${JUST_PROJECT_PREFIX}_NVIDIA_DEVICE_INDICES` environment variable to auto-add NVIDIA GPU capabilities to a docker container via `docker_compose_override`.
- GPU support in docker-compose is specified in https://docs.docker.com/compose/gpu-support/
- GPUs are identified via `${JUST_PROJECT_PREFIX}_NVIDIA_DEVICE_INDICES`, a space-delimited string of GPU indices
- GPU index ordering is as reported by `nvidia-smi --list-gpus`
- An empty or unset environment variable results in no GPU support
- Default indices can be obtained using `nvidia_tools::nvidia_device_indices`
=> docker-compose nvidia gpus

linux/just_files/docker_compose_override, tests/test-docker_compose_override.bsh
`docker_compose_override` use `*_NVIDIA_VISIBLE_DEVICES` and `*_NVIDIA_DRIVER_CAPABILITIES` to control docker-compose override for GPUs.  Related to PR #449.  Names mimic standard NVIDIA environment variables.
=> docker-compose nvidia capabilities

linux/bash_utils.bsh, linux/compat.bsh, linux/just_files/just_entrypoint.sh, linux/time_tools.bsh, linux/versions.bsh, tests/int/test-just_install_functions.bsh, tests/test-compat.bsh, tests/test-time_tools.bsh, tests/test-versions.bsh
added some functionality to support singularity in just
- Added singularity version checking. Support the different forks of singularity as "vendors", mainly `singularity`, `apptainer`, and `singularity-ce`
- Added compat flag for nvccli in singularity
- Added `get_timezone` finally so we can start setting `TZ` variable automatically
=> Singularity nvccli

docker/vsi_common/docker-compose.yml, docker/vsi_common/sphinx.Dockerfile, docker/vsi_common/sphinx.Pipfile, docker/vsi_common/sphinx.Pipfile.lock, docs/conf.py, linux/just_files/just_sphinx_functions.bsh
Sphinx build environment is reporting errors due to more recent python features, specifically for a project using python 3.10, sphinx is reporting `ImportError: cannot import name 'Literal' from 'typing'` due to sphinx's use of python 3.7.
Update sphinx to python 3.10 to avoid such errors.  Add environment variables `SPHINX_*_VERSION` to more easily control the sphinx build environment.  Re-lock the sphinx pipenv for the new python version.
=> sphinx python 3.10

docker/vsi_common/docker-compose.yml
add `-` to `SPHINX_*_VERSION` in docker-compose.yml to avoid "defaulting to blank string" warnings
=> SPHINX_*_VERSION default

linux/just_files/just_entrypoint.sh
Just need to make sure the entrypoint is not in /vsi or /src in case they are replaced by the symlink code
=> Fix warning message when /vsi is on nfs

linux/yarp.awk, tests/test-yarp.bsh
Yarp did not correctly count sequences as 2 spaces of indent. At some point in docker-compose 1.x they started using the "unindented sequences". This apparently didn't break anything we noticed, but we will need this moving forward.
=> Yarp rewrite

docs/style.rst, linux/compat_singularity.bsh, linux/just_files/container_functions.bsh, linux/just_files/docker_compose_override, linux/just_files/docker_functions.bsh, linux/just_files/singularity_functions.bsh, linux/versions.bsh, tests/int/test-docker_compose_override.bsh, tests/int/test-docker_functions.bsh, tests/int/test-new_just.bsh, tests/test-compat_singularity.bsh, tests/test-docker_compose_override.bsh, tests/test-docker_functions.bsh, tests/test-just_singularity_functions.bsh, tests/test-test_utils.bsh, tests/test_utils.bsh
In order to absolutely identify when you are in a container started by just, the environment variable `JUST_IN_CONTAINER` is now set. This is to distinguish between: e.g. "You are in a container due to CI" and "you are in a container started by just"
All just wrapped commands will add this environment variable, including:
- `Docker`
- `Just-docker-compose`
- `Singular-compose`
- `Singularity`
And in the future `Podman`, etc...
Other minor fixes include:
- Fixing singularity version check for apptainer, etc... 
- No longer need x-bugfix in `environment` since `JUST_IN_CONTAINER` will always be there.
=> Add JUST_IN_CONTAINER

linux/just_files/just_entrypoint.sh, tests/run_tests, tests/test-circular_source.bsh, tests/test-isin.bsh, tests/test-source_once.bsh, tests/test-time_tools.bsh, tests/testlib.bsh, vsi_common.env
There were a few issues surround source_once, mainly not being used enough.
- There's a old bug in bash pre 4.4 that was showing up in 4.0 to 4.3, where defining a function interactively corrupts the BASH_SOURCE stack. So shoving the mock function in a real file gets around that.
- Added using `source_once` in a few key places, drastically increasing load times, especially on WSL where Search the path on a maintained machine takes 60 ms, and on a unmaintained machine, will likely take much longer. But times that 200 files being loaded, adds up to a very noticeable amount. `source_once` is designed to be optional, but triggers a path search when unused.
=> Source once uses

linux/cuda_info.bsh, tests/test-cuda_info.bsh
`tcnn_cuda_architectures` to produce a comma delimited string of CUDA architectures for tiny-cuda-nn
=> tcnn_cuda_architectures 

linux/cuda_info.bsh, tests/test-cuda_info.bsh
`cuda_info::nvcc_gencodes` to create an nvcc gencode string from a delimited cuda capabilities string.  The intent here is to use the output of other cuda capability discovery functions (for example, `cmake_cuda_flags`) as input to this function.
=> nvcc_gencodes 

linux/just_files/just_entrypoint.sh
remove source_once from just_entrypoint as its causing problems with the `makeself` docker.  @andyneff is working on a more permanent fix.
=> source_once just_entrypoint

linux/just_files/Just_wrap, linux/just_files/just_entrypoint.sh, linux/just_files/just_functions.bsh, tests/test-new_just.bsh, tests/test-singularity_functions.bsh
TL;DR Now `extra_args` is properly set as a global variable in `just_entrypoint.sh`
---
We don't declare variables at the top level of a source able script very often (`colors.bsh` was the only other instance I saw), but in the case of `just_functions.bsh`, `extra_args` (et. al.) are declared as global variables, which is usually not a problem, but if this file is sourced inside a function (again, uncommon), then the variables that defined as integers, will be unset and lose their integer status.
Unfortunately once `source_once` was implemented correctly, `just_functions.bsh` was no longer being sourced multiple times covering up this mistake, and as soon as an internal just target uses `+=`, this problem finally manifests itself into a failure.
There are a few solutions considered:
1. …
=> Fix Extra Args bug

linux/cuda_info.bsh, tests/test-cuda_info.bsh
`cuda_info::torch_cuda_arch_list` Generate CUDA capabilities suitable for the `TORCH_CUDA_ARCH_LIST` environment variable.
=> cuda_info::torch_cuda_arch_list

linux/cuda_info.bsh, tests/test-cuda_info.bsh
cuda_info utilities to transform a `CMAKE_CUDA_ARCHITECTURES` statement into a `TORCH_CUDA_ARCH_LIST` or `TCNN_CUDA_ARCHITECTURES` statement.  
This allows projects to derive all application specific cuda architecture statements from a common source, which could be defined either by the user or  `cmake_cuda_architectures`.
For example:
```
if [ -z "${FOO_CMAKE_CUDA_ARCHITECTURES+set}" ]; then
CUDA_VERSION="${FOO_CUDA_VERSION}" discover_cuda_all
FOO_CMAKE_CUDA_ARCHITECTURES="$(cmake_cuda_architectures)"
fi
: ${FOO_TORCH_CUDA_ARCH_LIST="$(torch_cuda_arch_list_from_cmake "${FOO_CMAKE_CUDA_ARCHITECTURES}")"}
: ${FOO_TCNN_CUDA_ARCHITECTURES="$(tcnn_cuda_architectures_from_cmake "${FOO_CMAKE_CUDA_ARCHITECTURES}")"}
```
=> torch_cuda_arch_list_from_cmake & tcnn_cuda_architectures_from_cmake

linux/cuda_info.bsh, tests/test-cuda_info.bsh
`TCNN_CUDA_ARCHITECTURES` expects a comma delimiter.
https://github.com/NVlabs/tiny-cuda-nn/blob/212104156403bd87616c1a4f73a1c5f2c2e172a9/bindings/torch/setup.py#L43-L45
```
if "TCNN_CUDA_ARCHITECTURES" in os.environ and os.environ["TCNN_CUDA_ARCHITECTURES"]:
compute_capabilities = [int(x) for x in os.environ["TCNN_CUDA_ARCHITECTURES"].replace(";", ",").split(",")]
print(f"Obtained compute capabilities {compute_capabilities} from environment variable TCNN_CUDA_ARCHITECTURES")
```
=> tcnn_cuda_architectures_from_cmake delimiter

linux/just_files/just_entrypoint.sh
just_entrypoint save/return CWD to ensure entrypoint honors docker WORKDIR
=> just_entrypoint cwd

python/vsi/tools/network/wget.py
Upgrade the TLS protocol used in the wget python tool to avoid a security vulnerability.
=> wget tool: TLS v1 -> v1.2

linux/just_files/just_docker_functions.bsh
This is a first attempt to get the new invoke debug command to run against a docker-compose project.
This is currently not a feature of docker compose, so we have to roll our own wrapper for this. Think of this as a 60% solution against an experimental API that is likely to change again.
Hopefully this is good enough to work most of the time when we need something like this. Example:
```
just build # fails
```
Now we want to easily debug the issue, without a bunch of commenting out Dockerfile, which stages are being built, etc...
```
just docker-compose debug my_service_name
```
And if we are running against an intermittent issue and want to clear the cache for that stage specifically:
```
just docker-compose debug runner dep_common
```
=> Buildx invoke on docker-compose

linux/command_tools.bsh, tests/test-command_tools.bsh
A simple addition to `parse-generic` to support arguments that require one argument.
This is still far less strict than previous implementations like the docker compose parse which strictly only allows arguments that are defined in the code, but it opens up the use cases that `generic-parser` can work with by adding very little lift for the dev.
=> Add arguments with value to parse-generic

python/vsi/tools/patch_wheel.py, tests/int/test-python_script_patch_wheel.bsh
Use the wheel package to properly repackage a wheel, regenerating the `RECORDS` file and making pip and pip-tools happy when using the resulting wheel.
Since the `RECORDS` file is being regenerated now, I re-enabled the option to change the package name too.
=> Replace hacky patch with 'wheel pack'

linux/pre-commit_filter_lines
If you 'git push' without setup.env, you can get an error:
```
external/vsi_common/linux/pre-commit_filter_lines: line 7: /linux/aliases.bsh: No such file or directory
external/vsi_common/linux/pre-commit_filter_lines: line 15: : command not found
```
It should have had a default for `VSI_COMMON_DIR` in the first place
=> Fix error when pushing withhout setup.env

linux/just_files/just_troubleshooter_functions.bsh, linux/troubleshoot, tests/testlib.bsh, tests/troubleshoot/docker_buildx, tests/troubleshoot/git-lfs, tests/troubleshoot/nvidia_docker
Added new just troubleshoot feature. In your main project, you can:
1. Create a `.troubleshoot` file that points to other troubleshoot tests
2. Create a `.troubleshoot.d` directory containing troubleshoot tests
A troubleshoot test file contains pairs of functions:
- `troubleshoot_{test_name}` - Test to run (under `set -eu`), returns true when everything is ok. False when an issue is detected
- `error_{test_name}` - Prints _helpful_ error message when troubleshoot test fails
=> Just Troubleshoot

linux/just_files/just_install_functions.bsh
Now saying `--version 3.8` will get the latest 3.8 in conda, today that's 3.8.20.
=> Add ability to get latest version of minor

docker/tests/bash_test.Dockerfile, docker/tests/os.Dockerfile, docker/tests/python2.Dockerfile, docker/tests/python3.Dockerfile, docker/vsi_common/bashcov.Dockerfile, docker/vsi_common/makeself.Dockerfile, docker/vsi_common/pyinstaller.Dockerfile, docker/vsi_common/sphinx.Dockerfile, linux/just_files/just_install_functions.bsh, tests/test-docker_functions.bsh, tests/test-just_docker_functions.bsh
Replace `as` with `AS` to stop warnings and future risk of errors.
=> Fix dockerfile compatibility warnings
