VisionSystemsInc/vsi_common

docker/recipes/README.md
docker/recipes/docker-compose.yml
docker/recipes/recipe_ep.Dockerfile
docker/recipes/recipe_gosu.Dockerfile
docker/recipes/recipe_ninja.Dockerfile
docker/recipes/recipe_tini.Dockerfile
docker/recipes/recipe_tini_alpine.Dockerfile
linux/cuda_info.bsh

- Added Ninja Recipe, and use of SHELL
- Updated cuda table

Added ninja docker recipe and other small updates to recipes

---

docker/recipes/recipe_gosu.Dockerfile

Remove empty continuation lines in GOSU docker recipe.

Remove empty continuation lines in docker recipe

---

linux/cuda_info.bsh

Bail out if deviceQuery fails to run

guard deviceQuery in case it fails

---

Justfile
linux/Justfile_pipfile
linux/just_common.bsh
linux/just_functions.bsh
tests/int/test-Justfile_pipfile.bsh
tests/int/test-common_source.bsh
tests/run_tests.bsh
tests/test-common_source.bsh

- Added ability to run a different directory of tests
- Added Justfile_pipfile and tests to bootstrap Pipfile to match a docker image

Added Integration test directory

---

linux/dir_tools.bsh
linux/docker_compose_override
linux/docker_entrypoint.bsh
linux/docker_functions.bsh
linux/elements.bsh
linux/group_names
tests/test-dir_tools.bsh
tests/test-docker_compose_override.bsh
tests/test-docker_entrypoint.bsh
tests/test-docker_functions.bsh
tests/test-elements.bsh
tests/test-group_names.bsh
tests/test-just_docker_functions.bsh
tests/test_utils.bsh
tests/testlib.sh

This actually makes sure internal volume permissions are writable on container start, not for #7
However, completes part 2.2 of [this](https://github.com/VisionSystemsInc/vsi_common/pull/7#issuecomment-369656989)
@sgrichar

Compose volumes

---

linux/ask_question
linux/bin_utils.bsh
linux/colors.bsh
linux/common_source.sh

Andy,
Look at this right now because Joe said SO.

Initial Add

---

Justfile
linux/cuda_info.bsh
linux/new_just
tests/int/test-new_just.bsh

Fix build and add cuda10

---

linux/new_just
linux/uwecho.bsh
tests/test-uwecho.bsh

command substitution was eating the trailing newlines

Fix uwecho trailing newline

---

docs/python/modules.rst
docs/python/vsi.console.rst
docs/python/vsi.format.rst
docs/python/vsi.io.image.rst
docs/python/vsi.io.rst
docs/python/vsi.rst
docs/python/vsi.test.rst
docs/python/vsi.tools.network.rst
docs/python/vsi.tools.rst
docs/python/vsi.utils.rst
docs/python/vsi.vxl.rst
docs/python/vsi.windows.rst
python/vsi/tools/dir_util.py
python/vsi/tools/iter.py
python/vsi/tools/network/speedtest.py
python/vsi/tools/python.py
python/vsi/tools/redirect.py
python/vsi/vxl/create_scene_xml.py

sphinx documentation for speedtest.py

Sphinx python

---

python/vsi/tools/dir_util.py
python/vsi/tools/vdb.py
python/vsi/tools/vdb_rpdb.py
python/vsi/tools/vdb_rpdb2.py
python/vsi/tools/watch_dog.py

NumPy Style Python Documentation for:
python/vsi/tools/vdb.py
python/vsi/tools/vdb_rpdb.py
python/vsi/tools/vdb_rpdb2.py
python/vsi/tools/watch_dog.py
Made a correction to:
python/vsi/tools/dir_util.py

Documentation for the rest of the tools/ files.

---

Justfile
docker-compose.yml
docker/tests/Pipfile2
docker/tests/Pipfile2.lock
linux/docker_functions.bsh
linux/example_just
linux/just_docker_functions.bsh
linux/just_functions.bsh
linux/just_robodoc_functions.bsh
linux/new_just
python/vsi/test/test_python.py
python/vsi/tools/dir_util.py
python/vsi/tools/python.py
python/vsi/tools/vdb_rpdb2.py
tests/test-docker_functions.bsh
tests/test-just_functions.bsh

- Simplify _post_build some
- Simplify `justify` calls
- Added `docker_cp_image`

Fix decorators

---

python/vsi/test/test_python.py
python/vsi/tools/python.py

Added argv context

---

python/vsi/test/test_python.py
python/vsi/tools/python.py

Added nested dict operations

---

linux/docker_entrypoint.bsh

fix an issue where docker_link_mounts is trying to symlink over a directory

fix issue where docker_link_mounts is trying to symlink over a dir

---

linux/cuda_info.bsh

Added Turing to to CUDA Info families

---

linux/cuda_info.bsh

Fix awk expansion line

---

linux/just
linux/just_docker_functions.bsh
linux/just_env
linux/new_just
linux/time_tools.bsh
tests/int/test-new_just.bsh

Closes #92

---

linux/new_just
python/vsi/tools/python.py
tests/int/test-common_source.bsh

- Add readability to new_just dockerfiles
- Improve `nested_update`

Unit19 wayne patch1

---

linux/new_just

Add timezone

---

env.bsh

- Fix warning on setup.env source

Merge in additional 0.2.0 changes

---

linux/new_just

Wrong if statement

---

linux/just_version.bsh

Dev bump [skip ci]

---

linux/Just_wrap
linux/docker_compose_override
linux/just_functions.bsh
linux/new_just
tests/int/test-common_source.bsh
tests/int/test-new_just.bsh
tests/test-docker_compose_override.bsh

No wrap merge

---

linux/just_sphinx_functions.bsh

Fix sphinx build

---

.gitattributes
linux/just_functions.bsh

Small changes during terra_dsm debugging:
- add `*.Justfile` to `.gitattributes`
- change `set_temp_array` depreciation message

gitattributes and depreciation message

---

appveyor.yml
tests/test-docker_compose_override.bsh
tests/test-just_singularity_functions.bsh

Fix appveyor custom clone_script being bad
- Instead of fixing custom script, removed it, and allow the default to run instead. Moved submodule update to `install` section

Appveyor fun

---

linux/just_common.bsh
linux/just_git_functions.bsh

Fix error when JUST_SETTINGS not set

---

python/vsi/utils/geometry_utils.py
python/vsi/utils/mesh_utils.py

remove vtk dependency for PLY mesh read/write

Python util updates

---

python/vsi/utils/geometry_utils.py

Change quaternion ordering in vsi.utils.geometry_utils to [w, x ,y ,z] (i.e. real component first) to better match what seems to be the more common convention.  Note that vxl uses the opposite order.

change quaternion ordering

---

Justfile
docker/tests/bash_test.Dockerfile
docker/tests/python2.Dockerfile
docker/tests/python3.Dockerfile
docker/vsi_common/sphinx.Dockerfile
docs/just/files.rst
linux/.just
linux/Just_wrap
linux/command_tools.bsh
linux/elements.bsh
linux/git_safe_update
linux/just
linux/just_common.bsh
linux/just_entrypoint.sh
linux/just_entrypoint_user_functions.bsh
linux/just_env
linux/just_functions.bsh
linux/just_git_functions.bsh
linux/just_sphinx_functions.bsh
linux/just_test_functions.bsh
linux/just_version.bsh
linux/new_just
tests/test-circular_source.bsh
tests/test-git_safe_update.bsh
tests/test-just_entrypoint_user_functions.bsh
tests/test-just_wrap.bsh

Cleanup 01 20

---

.circleci/config.yml
Justfile
docker-compose.yml
docker/tests/bash_test.Dockerfile
docker/tests/bash_test.Justfile
docker/vsi_common/bashcov.Dockerfile
linux/docker_functions.bsh
linux/just_docker_functions.bsh
linux/just_entrypoint_functions
linux/just_git_functions.bsh
linux/new_just
linux/requirements.bsh
tests/int/test-new_just.bsh
tests/test-docker_functions.bsh
tests/test-just_docker_functions.bsh
tests/test-requirements.bsh
vsi_common.env

Add tools for caching docker image for faster CI

Ci restore

---

linux/ci_load.py
linux/colors.bsh
linux/debug.bsh
linux/debug_readline.py
linux/docker_functions.bsh
linux/just_git_functions.bsh
tests/test-docker_functions.bsh

- Added ci_load script
- Added bash debugger
- Added new service_names function using `yarp` instead of `sed` insanity.

Service names2

---

linux/.just

enable shell syntax highlighting

---

freeze/just_wrapper
linux/compat.bsh
linux/cuda_info.bsh
linux/docker_functions.bsh
linux/just
linux/just_common.bsh
linux/just_docker_functions.bsh
linux/just_functions.bsh
linux/just_git_functions.bsh
linux/just_makeself_functions.bsh
linux/new_just
linux/python_tools.bsh
linux/requirements.bsh
linux/uwecho.bsh
python/vsi/test/utils.py
tests/int/test-new_just.bsh
tests/test-python_tools.bsh

Adding features to help freeze code, like pyinstaller and makeself

Adding deploy capabilities

---

python/vsi/utils/plot_utils.py

Add new "imshow_with_colorbar" function and remove scikit-image dependency from vsi.utils.plot_utils

Plot utils update

---

linux/ci_load.py

- Restore recipes only when recipes are present (protect with `if ... self.recipes:`)
- Remove unused variables from build_stages

ci_load minor updates

---

appveyor.yml

Fix https://www.msys2.org/news/#2020-06-29-new-packagers

Appveyor keys

---

docker/vsi_common/sphinx.Pipfile.lock
linux/ask_question
linux/time_tools.bsh

- Added help to ask_question
- Added perl fallback to getting accurate time

Update sphinx to 3.2.1

---

python/vsi/utils/geometry_utils.py

- remove redundant rotation format conversion functions
- add a couple rigid transform (RT matrix) manipulation functions
- remove some extra whitespace causing flake8 warnings

geometry_utils updates

---

python/vsi/tools/time_utils.py

Moving time_utils from terra DSM into vsi_common, at Andy's suggestion.

time_utils task timer

---

.circleci/config.yml

Windows on CircleCI

---

.circleci/config.yml

change circleci run_windows_test working directory to `~/repo`

circleci windows working dir

---

.circleci/config.yml
.travis.yml
linux/git_mirror

Get int tests to run where intended

Get CI running

---

.appveyor.yml
linux/web_tools.bsh
tests/int/test-web_tools.bsh
tests/test-web_tools.bsh

- Tries all methods of download, until one succeeds

Improve download_to_stdout

---

linux/common_source.sh
linux/compat.bsh
linux/cuda_info.bsh
linux/just_files/Just_wrap
linux/just_files/just_install_functions.bsh
linux/just_files/singularity_functions.bsh
linux/requirements.bsh
linux/signal_tools.bsh
tests/test-compat.bsh
tests/test-just_singularity_functions.bsh
tests/test-requirements.bsh
tests/test-singularity_functions.bsh
tests/test_utils.bsh
tests/testlib.bsh
vsi_common.env

- Fix instance name for singularity instances

October work

---

python/vsi/tools/time_utils.py

Format the average duration per task in addition to the total duration. I don't want to have to do mental math!
E.g.
> Finished 4 filter points tasks in 4 minutes, and 32 seconds for an average time of 68 seconds per task.
becomes
> Finished 4 filter points tasks in 4 minutes, and 32 seconds for an average time of 1 minute, and 8 seconds per task.

STYLE: Task Timer pretty print

---

python/vsi/utils/mesh_utils.py
python/vsi/utils/plot_utils.py

Some minor enhancements to plotting and mesh-saving modules:
- handle non-triangle meshes in save_mesh_ply()
- add method for plotting (projected) cuboid into an image
- reduce precision that point clouds are saved with to reduce file size

Python utils updates

---

linux/compat.bsh
tests/test-compat.bsh

Add bash_bug_uncaught_unbound_on_exit_trap

---

linux/just_files/just_install_functions.bsh
tests/int/test-just_install_functions.bsh

`just_install_functions` install directly to specified directory (rather than a subdirectory).

just_install_functions direct install

---

docker/vsi_common/sphinx.Justfile
docker/vsi_common/sphinx.Pipfile.lock
docs/conf.py

- Added default behavior to intersphinx target

Update sphinx version

---

.appveyor.yml
linux/aliases.bsh
linux/cuda_info.bsh
linux/elements.bsh
linux/just_files/docker_functions.bsh
linux/linux_accounts.bsh
tests/test-cuda_info.bsh

- Small PR to update the info in cuda_info
- Break up large functions into smaller manageable functions
- Unit tests for new structure

Cuda info update

---

linux/cuda_info.bsh
linux/just
linux/just_files/Just_wrap
linux/just_files/just_entrypoint.sh
linux/time_tools.bsh
tests/test-new_just.bsh

- This is to allow just_entrypoint to transfer arrays to just
- Partially updated for cuda 11.3 only because it was failing on my machine. A more proper cuda update will come later
- Fixed a bug that occurred if you have python 2 and not 3 installed
- Fixed a bug (in a unit tests) if your username had special characters in it.

Make just a function

---

docker/tests/bash_test.Justfile

Fix to run tests locally

---

linux/cuda_info.bsh
linux/just_files/just_git_functions.bsh
tests/int/test-just_git_functions.bsh
tests/test-cuda_info.bsh

Reattach head with slashes

---

README.md
docker/tests/bash_test.Dockerfile
docker/tests/os.Dockerfile
linux/bash_utils.bsh
linux/command_tools.bsh
linux/common_source.sh
linux/compat.bsh
linux/git_mirror
linux/just_files/new_just
linux/just_git_airgap_repo.bsh
linux/versions.bsh
tests/int/test-compat.bsh
tests/run_tests
tests/test-bash_utils.bsh
tests/test-common_source.bsh
tests/test-compat.bsh
tests/test-docker_compose_override.bsh
tests/test-just_wrap.bsh
tests/testlib.bsh
vsi_common.env

- Re-fix just_version being set in new_just
- Removed need for `screen` from unit tests
- Added `run_bash_rc_file`

Andy 20210917

---

linux/just_files/just_install_functions.bsh

Add hosttype check for macos

---

linux/common_source.sh

Small update

---

linux/just_files/just_install_functions.bsh

Horray for random name changes!

Support new cmake filenames

---

linux/command_tools.bsh
linux/just_files/just_install_functions.bsh

- Made --help return without stack trace

Added list feature to conda python install

---

linux/just_files/docker_functions.bsh

Fix take two

---

linux/cuda_info.bsh
linux/web_tools.bsh
python/vsi/image.py
python/vsi/tools/file_util.py
setup.py

- Also updated cuda_info
- Added listing open ports to web_tools

Add vsi.image

---

docs/conf.py
python/vsi/image.py

#425 PR broke the docs, and it wasn't noticed because CI didn't fully run for some reason, this fixed the docs again.

Ci didnt run

---

linux/just_files/just_docker_functions.bsh

Note: This change is not docker-compose 1.x compatible

Fix docker-compose api change

---

linux/cuda_info.bsh

Added cuda 12.0.0, 12.0.1, and 12.1.0

Updated for cuda 12.1.0

---

Justfile
docker/tests/python2.Dockerfile
docker/tests/python3.Dockerfile
docker/vsi_common/pyinstaller.Dockerfile
docker/vsi_common/sphinx.Dockerfile

- Add consistent use of nullglob
- Add self delete recipe scripts to prevent double running
- For bugs and speed

Update recipe and blueprints

---

linux/cuda_info.bsh

Added a common function to check if we have a GPU, since this is a common occurrence that gets more complicated with WSL, Windows, etc...

Added GPU checks

---

linux/just_files/docker_compose_override
tests/test-docker_compose_override.bsh

Also forgot to test multiple services

Forgot to clear the array between services

---

linux/cuda_info.bsh
tests/test-cuda_info.bsh

Fixes bug discovered during demo

Fix 11.4 86 bug

---

docs/vsi_domains.py
linux/just_files/docker_compose_override
linux/just_files/docker_functions.bsh
linux/yarp.awk
tests/int/test-new_just.bsh
tests/test-docker_functions.bsh
tests/test-singularity_functions.bsh
tests/test-yarp.bsh

Fix for docker compose 2.22.0, where indents changes... attempt 3

Docker compose 2.22.0

---

linux/cuda_info.bsh

Update to CUDA 12.3

---

linux/just_files/just_install_functions.bsh
tests/int/test-just_install_functions.bsh

Default to miniforge instead of miniconda

Default to miniforge

---

linux/just_files/just_docker_functions.bsh
linux/just_files/just_functions.bsh

Added a way to set build args for recipes.
Added a first go at `just_error`

Add build args for recipes

---

linux/just_files/just_docker_functions.bsh
tests/test-just_docker_functions.bsh

- Also fixed two old style `docker-compose` calls with `docker compose`

Make docker compose debug more user friendly

---

linux/cuda_info.bsh

Updated with info up to 12.6.1

Update latest cuda info

---

python/vsi/image.py

Add optional debugging visualizations for cross correlation in vsi.image.

vsi.image debug visualizations

---

python/vsi/image.py

More updates to vsi.image that I forgot to include in MR #515.
- missing import fix
- JSON serializable outputs
- out of bounds checking
- handle duplicate peak values

vsi.image updates

---

linux/just_files/just_docker_functions.bsh

Updating docker recipes and also fixed hard coding of bash in invoke command for docker-compose `debug` feature

Update docker recipe fix

---

.appveyor.yml
.circleci/config.yml
.github/workflows/macos.yml
linux/just_files/just_archive.bsh
tests/int/test-just_archive.bsh

`just git archive` - perform a recursive `git archive` on a git repo including submodules, saving the result to a tarball. The archive will be created from the current repo (i.e., `HEAD`) & current submodules (i.e., `HEAD` of each submodule).

just git archive
